#Requires -Version 5.1
<#
.SYNOPSIS
    Builds a Release build and packages bin\Release\net481 into dist\Encodex-<version>.zip,
    then regenerates update.xml (version / download url / sha256).

.DESCRIPTION
    Steps performed:
      1. dotnet build -c Release
      2. Copy the build output to a staging folder, excluding *.pdb
      3. Create dist\Encodex-<version>.zip (files at the zip root, no nested folders)
      4. Compute SHA-256 and rewrite update.xml

    Afterwards: create a GitHub Release with tag v<version>, attach the zip,
    and commit the updated update.xml to the main branch.

.PARAMETER RepoOwner
    GitHub user or organization name used to build the download URL in update.xml.

.PARAMETER Notes
    Release notes written into the <notes> element of update.xml.

.EXAMPLE
    .\pack-release.ps1 -RepoOwner myname -Notes "1. Bug fixes"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$RepoOwner,

    [string]$Notes = "See GitHub release."
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Push-Location $projectRoot
try {
    # --- 1. Build -------------------------------------------------------------
    Write-Host "[1/5] Building Release..." -ForegroundColor Cyan
    dotnet build Encodex.csproj -c Release --nologo -v minimal
    if ($LASTEXITCODE -ne 0) { throw "Build failed." }

    # --- 2. Read the assembly version ------------------------------------------
    $assemblyInfo = Join-Path $projectRoot "AssemblyInfo.cs"
    if ((Get-Content $assemblyInfo -Raw) -notmatch 'AssemblyVersion\("([^"]+)"\)') {
        throw "Could not read AssemblyVersion from AssemblyInfo.cs"
    }
    $version = $Matches[1]
    Write-Host "[2/5] Version: $version" -ForegroundColor Cyan

    # --- 3. Stage the output (exclude debug symbols) ----------------------------
    Write-Host "[3/5] Staging files (excluding *.pdb)..." -ForegroundColor Cyan
    $sourceDir  = Join-Path $projectRoot "bin\Release\net481"
    $stagingDir = Join-Path $projectRoot "dist\staging"
    if (Test-Path $stagingDir) { Remove-Item $stagingDir -Recurse -Force }
    New-Item -ItemType Directory -Path $stagingDir | Out-Null
    Get-ChildItem $sourceDir -File |
        Where-Object { $_.Extension -ne ".pdb" } |
        Copy-Item -Destination $stagingDir

    # --- 4. Create the zip at the dist root ------------------------------------
    Write-Host "[4/5] Creating zip..." -ForegroundColor Cyan
    $distDir = Join-Path $projectRoot "dist"
    $zipPath = Join-Path $distDir "Encodex-$version.zip"
    if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
    # Compress the staging folder's *contents*: files land at the zip root.
    Compress-Archive -Path "$stagingDir\*" -DestinationPath $zipPath
    Remove-Item $stagingDir -Recurse -Force

    $sha256 = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $zipSizeMb = [math]::Round((Get-Item $zipPath).Length / 1MB, 2)

    # --- 5. Regenerate update.xml -----------------------------------------------
    Write-Host "[5/5] Updating update.xml..." -ForegroundColor Cyan
    $downloadUrl = "https://github.com/$RepoOwner/Encodex/releases/download/v$version/Encodex-$version.zip"
    $escapedNotes = [System.Security.SecurityElement]::Escape($Notes)
    $manifest = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Release manifest consumed by AppUpdateService.
     Regenerated by pack-release.ps1 on every release: bump the AssemblyVersion in
     AssemblyInfo.cs first, then run the script and commit the resulting update.xml. -->
<update>
  <version>$version</version>
  <url>$downloadUrl</url>
  <sha256>$sha256</sha256>
  <mandatory>false</mandatory>
  <notes>$escapedNotes</notes>
</update>
"@
    Set-Content -Path (Join-Path $projectRoot "update.xml") -Value $manifest -Encoding UTF8

    Write-Host ""
    Write-Host "Done. Publish steps:" -ForegroundColor Green
    Write-Host "  1. Create a GitHub Release with tag v$version"
    Write-Host "  2. Attach  dist\Encodex-$version.zip  ($zipSizeMb MB)"
    Write-Host "  3. Commit the updated update.xml to the main branch"
    Write-Host ""
    Write-Host "  SHA-256: $sha256"
}
finally {
    Pop-Location
}
